version: "3.2"
services:
  mailhog:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
  db:
    image: ledgersmb/ledgersmb-dev-postgres
    environment:
      POSTGRES_PASSWORD: abc
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - target: /var/lib/postgresql/data
        type: tmpfs
#        tmpfs:
#          size: 1000000000
  selenium:
    image: wernight/phantomjs:2.1.1
    command: phantomjs --webdriver=4422
    stop_signal: SIGKILL
    expose:
      - 4422
    environment:
      LANG: en_US.UTF-8
  lsmb:
    depends_on:
      - db
      - selenium
      - mailhog
    image: ${LSMB_IMAGE:-ledgersmb/ledgersmb-dev-lsmb}
    links:
      - "db:postgres"
    volumes:
      - type: bind
        target: /srv/ledgersmb
        source: ${PWD}
    environment:
      - PERL5OPT
      - HARNESS_PERL_SWITCHES
      - RELEASE_TESTING=1
      - HARNESS_RULESFILE="t/testrules.yml"
      - DEVEL_COVER_OPTIONS
      - LSMB_BASE_URL=http://proxy:80
      - PSGI_BASE_URL=http://lsmb:5762
      - LSMB_TEST_DB=1
      - LSMB_NEW_DB=lsmbtestdb
      - COA_TESTING=1
      - REMOTE_SERVER_ADDR=selenium
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=abc
      - SSMTP_HOSTNAME=mailhog
      - SSMTP_MAILHUB=mailhog:1025
  proxy:
    image: ledgersmb/ledgersmb-dev-nginx
    ports:
      - 80:80
    depends_on:
      - lsmb
    volumes:
      - type: bind
        target: /srv/ledgersmb
        source: ${PWD}


volumes:
  dbdata:

